image:
  file: .gitpod.dockerfile
tasks:
  - init: |
      export PIP_USER=no
      pre-commit install
      pre-commit install-hooks
      exit
  - init: |
      export PIP_USER=no
      poetry install -E docs
