github:
  prebuilds:
    addBadge: true
    addCheck: prevent-merge-on-error
    master: true
    pullRequests: true

vscode:
  extensions:
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - ms-python.python

ports:
  # Mkdocs local server; start it with `poe docs`
  - port: 8000
    onOpen: notify

tasks:
  - init: direnv allow
