# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install uv
      - |
        VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH \
        uv sync --active --frozen --only-group docs
